In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [15]:
# import gpxpy
# gpx = gpxpy.parse(open('./Dataset/PTM Strava Data/bike/Laramie_Enduro_2014.gpx'))
data_csv = pd.read_csv("./filtered.csv")#读取filtered file
trajectory1 = np.array(data_csv, dtype=np.float64)  # trajectory1[:, 2:9] 原为2个数据 现为8个

In [ ]:
# print("{} track(s)".format(len(gpx.tracks)))
# track = gpx.tracks[0]

# print("{} segment(s)".format(len(track.segments)))
# segment = track.segments[0]

# print("{} point(s)".format(len(segment.points)))

In [ ]:
# segment_length = segment.length_3d()
# for point_idx, point in enumerate(segment.points):
#     print(point,point_idx)

In [16]:


# data = []
# segment_length = segment.length_3d()
# for point_idx, point in enumerate(segment.points):
#     data.append([point.longitude, point.latitude,
#                  point.elevation, point.time, segment.get_speed(point_idx)])
    
from pandas import DataFrame

# columns = ['Longitude', 'Latitude', 'Altitude', 'Time', 'Actual_Speed']
columns = ['Global_Time', 'Global_X', 'Global_Y', 'v_Vel', 'v_Acc']
df = DataFrame(trajectory1, columns=columns)
# Global time 为标准时间单位：1/100s
# 1ft=0.3048m
df.head()

   Global_Time     Global_X     Global_Y  v_Vel  v_Acc
0          0.0  679864.4007  419283.8057  11.12    0.0
1          1.0  679864.4159  419284.1440  11.12    0.0
2          2.0  679864.4315  419284.4826  11.12    0.0
3          3.0  679864.4467  419284.8213  11.12    0.0
4          4.0  679864.4623  419285.1599  11.12    0.0

In [ ]:
# calculate distance based on haversine and time difference
# convert time to seconds

def time_diff_seconds(diff):
    return diff.total_seconds()
    
# (df['Time'][1] - df['Time'][0]) .total_seconds()

# print(time_diff_seconds(df['Time'][1],df['Time'][0]))

# calculate diff between times

df['Time_diff'] = df['Global_Time'].diff()

df['Time_diff'] = df['Time_diff'].apply(lambda x : time_diff_seconds(x))


df.tail(3)

In [22]:
# calculate haversine distance and based on that calculate calculated speed

# from haversine import haversine, Unit
# lyon = (45.7597, 4.8422) # (lat, lon)
# paris = (48.8567, 2.3508)
# haversine(lyon, paris)

# df['Haversine_Distance']=0

# for i in range(len(df)):
#     if i != 0:
#         d=0
        
#         loc1 = (df['Latitude'][i-1],df['Longitude'][i-1])
#         loc2 = (df['Latitude'][i],df['Longitude'][i])
        
#         d = haversine(loc1,loc2)*1000
# #         print(d)
#         df['Haversine_Distance'][i] = d
from math import radians, cos, sin, asin, sqrt

def haversine(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance between two points
    on the earth (specified in decimal degrees)
    """
    # Convert decimal degrees to radians
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

    # Haversine formula
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a))
    r = 6371 # Radius of earth in kilometers. Use 3956 for miles
    return c * r


new_df = df.head(100)
new_df['Pred_X'] = new_df['Global_X'] 
new_df['Pred_Y'] = new_df['Global_Y'] 

# for i in range(len(new_df)):
#     new_df['Pred_Lat'][i] = new_df['Latitude'][i+1]
#     new_df['Pred_Lon'][i] = new_df['Longitude'][i+1]
    

    
    
#     if i != 0:
#         d=0
        
#         loc1 = (new_df['Latitude'][i-1],new_df['Longitude'][i-1])
#         loc2 = (new_df['Latitude'][i],new_df['Longitude'][i])
        
#         d = haversine(loc1,loc2)*1000
# #         print(d)
#         new_df['Haversine_Distance'][i] = d

new_df

C:\Users\11396\AppData\Local\Temp\ipykernel_52488\3243676317.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Pred_X'] = new_df['Global_X']
C:\Users\11396\AppData\Local\Temp\ipykernel_52488\3243676317.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Pred_Y'] = new_df['Global_Y']

,Global_Time,Global_X,Global_Y,v_Vel,v_Acc,Time_diff,Pred_X,Pred_Y
0,0.0,679864.4007,419283.8057,11.12,0.0,NaN,679864.4007,419283.8057
1,1.0,679864.4159,419284.1440,11.12,0.0,1.0,679864.4159,419284.1440
2,2.0,679864.4315,419284.4826,11.12,0.0,1.0,679864.4315,419284.4826
3,3.0,679864.4467,419284.8213,11.12,0.0,1.0,679864.4467,419284.8213
4,4.0,679864.4623,419285.1599,11.12,0.0,1.0,679864.4623,419285.1599
...,...,...,...,...,...,...,...,...
95,95.0,679864.9198,419294.4158,0.11,0.0,1.0,679864.9198,419294.4158
96,96.0,679864.9207,419294.4191,0.12,0.0,1.0,679864.9207,419294.4191
97,97.0,679864.9216,419294.4228,0.11,0.0,1.0,679864.9216,419294.4228
98,98.0,679864.9228,419294.4261,0.11,0.0,1.0,679864.9228,419294.4261
99,99.0,679864.9237,419294.4295,0.11,0.0,1.0,679864.9237,419294.4295

In [21]:
for i in range(len(new_df)):
    print(i)
    if i != len(new_df)-1:
        new_df['Pred_X'][i] = float(new_df['Global_X'][i+1])
        new_df['Pred_Y'][i] = float(new_df['Global_Y'][i+1])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99

C:\Users\11396\AppData\Local\Temp\ipykernel_52488\42002613.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Pred_X'][i] = float(new_df['Global_X'][i+1])
C:\Users\11396\AppData\Local\Temp\ipykernel_52488\42002613.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Pred_Y'][i] = float(new_df['Global_Y'][i+1])

# Too Much Slow Step

In [24]:
# haversine distance 

new_df['Haversine_Distance'] =float(0)

for i in range(len(new_df)):
    if i != 0:
        # loc1=(new_df['Global_X'][i-1],new_df['Global_Y'][i-1])
        # loc2=(new_df['Global_X'][i],new_df['Global_Y'][i])
        
        d = haversine(new_df['Global_X'][i-1],new_df['Global_Y'][i-1],new_df['Global_X'][i],new_df['Global_Y'][i])*1000       #1000不一定
        print(d)
        new_df['Haversine_Distance'][i]=float(d)

new_df

37624.55247366726
37658.10860870855
37668.67176155058
37657.743167544366
37657.210786251795
37668.415773502216
37623.60415456168
37656.95201687783
37667.74089301291
37656.61307834775
37656.29666026372
37667.399629553576
37622.55392720761
37656.02787698705
37666.718594229984
37655.70838353096
37655.4885070129
37621.86027169543
37666.30374805824
37654.867238943625
37654.946562612095
37665.706395943904
37654.65688497826
37620.96217850559
37665.494632885486
37654.05512631362
37654.059798110065
38877.134889301844
35396.88028907467
27078.629649256352
20872.49386806171
13966.537089654952
6505.061708769903
4136.733204897193
956.3191192788042
989.6761603663222
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
33.358475556269696
0.0
133.7401190559153
245.2966507814809
401.21984575774053
413.00735570558277
367.9437307096033
379.7867549098744
368.1769913632979
379.78532566170264
379.03225830336464
367.941644366064
379.7831724453514
367.94082672811254
379.0306426566253
369.0198042063452
379.02984396272745
368.71189542688336
379.02903423989653
401.21406797982365
379.7773996926924
368.170291343225
379.7759800606586
367.93663688280435
379.0265876212137
379.77383160326474
367.93539568066103
379.2508254981852
368.70373819492806
379.024580452702
368.70227801046747
379.02377251750556
367.93291042418565
413.2604094270715
367.93205915037555
379.02213324519045
368.6978112612054
379.02133202495975
368.69635910201725
379.2448458071429
367.9295719534049
379.7623830296705
379.0193359059125
368.69267880532203
379.0185244251416
368.1579973275365
379.7588350676529
367.9266811611941
412.2981958356723
368.68822897359644
379.0160958434037

C:\Users\11396\AppData\Local\Temp\ipykernel_52488\139898633.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Haversine_Distance'] =float(0)
C:\Users\11396\AppData\Local\Temp\ipykernel_52488\139898633.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Haversine_Distance'][i]=float(d)

,Global_Time,Global_X,Global_Y,v_Vel,v_Acc,Time_diff,Pred_X,Pred_Y,Haversine_Distance
0,0.0,679864.4007,419283.8057,11.12,0.0,NaN,679864.4007,419283.8057,0.000000
1,1.0,679864.4159,419284.1440,11.12,0.0,1.0,679864.4159,419284.1440,37624.552474
2,2.0,679864.4315,419284.4826,11.12,0.0,1.0,679864.4315,419284.4826,37658.108609
3,3.0,679864.4467,419284.8213,11.12,0.0,1.0,679864.4467,419284.8213,37668.671762
4,4.0,679864.4623,419285.1599,11.12,0.0,1.0,679864.4623,419285.1599,37657.743168
...,...,...,...,...,...,...,...,...,...
95,95.0,679864.9198,419294.4158,0.11,0.0,1.0,679864.9198,419294.4158,379.758835
96,96.0,679864.9207,419294.4191,0.12,0.0,1.0,679864.9207,419294.4191,367.926681
97,97.0,679864.9216,419294.4228,0.11,0.0,1.0,679864.9216,419294.4228,412.298196
98,98.0,679864.9228,419294.4261,0.11,0.0,1.0,679864.9228,419294.4261,368.688229
99,99.0,679864.9237,419294.4295,0.11,0.0,1.0,679864.9237,419294.4295,379.016096

In [25]:

# new_df
# new_df['Time_diff'][0]=1
# new_df['Calculated_Speed'] = new_df[new_df.apply(lambda x: x['Haversine_Distance']/x['Time_diff'])]
# new_df[['Haversine_Distance']].apply(lambda x: print(x))
# new_df['Calculated_Speed'] = new_df[lambda x :  x['Haversine_Distance'] / x['Time_diff'] ]

new_df['Calculated_Speed'] = float(0)
for i in range(len(new_df)):
    
    new_df['Calculated_Speed'][i] = new_df['Haversine_Distance'][i] / new_df['Time_diff'][i]

new_df

C:\Users\11396\AppData\Local\Temp\ipykernel_52488\1841234296.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Calculated_Speed'] = float(0)
C:\Users\11396\AppData\Local\Temp\ipykernel_52488\1841234296.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Calculated_Speed'][i] = new_df['Haversine_Distance'][i] / new_df['Time_diff'][i]

,Global_Time,Global_X,Global_Y,v_Vel,v_Acc,Time_diff,Pred_X,Pred_Y,Haversine_Distance,Calculated_Speed
0,0.0,679864.4007,419283.8057,11.12,0.0,NaN,679864.4007,419283.8057,0.000000,NaN
1,1.0,679864.4159,419284.1440,11.12,0.0,1.0,679864.4159,419284.1440,37624.552474,37624.552474
2,2.0,679864.4315,419284.4826,11.12,0.0,1.0,679864.4315,419284.4826,37658.108609,37658.108609
3,3.0,679864.4467,419284.8213,11.12,0.0,1.0,679864.4467,419284.8213,37668.671762,37668.671762
4,4.0,679864.4623,419285.1599,11.12,0.0,1.0,679864.4623,419285.1599,37657.743168,37657.743168
...,...,...,...,...,...,...,...,...,...,...
95,95.0,679864.9198,419294.4158,0.11,0.0,1.0,679864.9198,419294.4158,379.758835,379.758835
96,96.0,679864.9207,419294.4191,0.12,0.0,1.0,679864.9207,419294.4191,367.926681,367.926681
97,97.0,679864.9216,419294.4228,0.11,0.0,1.0,679864.9216,419294.4228,412.298196,412.298196
98,98.0,679864.9228,419294.4261,0.11,0.0,1.0,679864.9228,419294.4261,368.688229,368.688229
99,99.0,679864.9237,419294.4295,0.11,0.0,1.0,679864.9237,419294.4295,379.016096,379.016096

In [27]:
# new_df = new_df.drop([['Altitude','Time']],axis=1)
new_df = new_df.drop(['Global_Time'],axis=1)


new_df

,Global_X,Global_Y,v_Vel,v_Acc,Time_diff,Pred_X,Pred_Y,Haversine_Distance,Calculated_Speed
0,679864.4007,419283.8057,11.12,0.0,NaN,679864.4007,419283.8057,0.000000,NaN
1,679864.4159,419284.1440,11.12,0.0,1.0,679864.4159,419284.1440,37624.552474,37624.552474
2,679864.4315,419284.4826,11.12,0.0,1.0,679864.4315,419284.4826,37658.108609,37658.108609
3,679864.4467,419284.8213,11.12,0.0,1.0,679864.4467,419284.8213,37668.671762,37668.671762
4,679864.4623,419285.1599,11.12,0.0,1.0,679864.4623,419285.1599,37657.743168,37657.743168
...,...,...,...,...,...,...,...,...,...
95,679864.9198,419294.4158,0.11,0.0,1.0,679864.9198,419294.4158,379.758835,379.758835
96,679864.9207,419294.4191,0.12,0.0,1.0,679864.9207,419294.4191,367.926681,367.926681
97,679864.9216,419294.4228,0.11,0.0,1.0,679864.9216,419294.4228,412.298196,412.298196
98,679864.9228,419294.4261,0.11,0.0,1.0,679864.9228,419294.4261,368.688229,368.688229
99,679864.9237,419294.4295,0.11,0.0,1.0,679864.9237,419294.4295,379.016096,379.016096

In [28]:
new_df.to_csv('DataSet.csv')